### ISSUE TITLE
Can you explain how this data pack works better?

### ISSUE THREAD

**Issue by SoBeeIt** [sniffercraft34/SmartChunkLoader#1]
I can get the gist reading the mcfunction files, although I do not get the broader view such as a Trace(in debugging or coding). And yes I did read: "It periodically manages chunk loading and unloading to ensure that only necessary chunks are loaded around players, thus optimizing performance. It does this by using a timer system to reduce the frequency of these operations to every 5 seconds, rather than every game tick, to minimize performance impacts. "

**Comment by sniffercraft34** [comment]
So basically, when you are in the world, it loads only chunks that are needed, and then stops loading the chunks that are no longer needed, providing a little performance boost when compared to vanilla. That is all I can really say. I do hope it helps!

**Comment by NXTler** [comment]
Is this something that has been done before in other mods like Lithium, Modernfix ect.?

**Comment by sniffercraft34** [comment]
Not really, lithium changes a few vanilla mechanics to work better, and modernfix improves loading speeds.

**Comment by NXTler** [comment]
Very cool, I was wondering because I saw a decend loading speed uplift during testing and wondered if other performance mods would effect it. How do you determine which chunks are needed and which not? 

EDIT: No need to explain, I just read the explaination.
